name: "报告Bug"
labels: [bug]
description: 如果想报告运行出错请用此模板
body:
  - type: input
    id: py-version
    attributes:
      label: 使用的Python版本
      placeholder: '3.7'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 使用的发行版本
      placeholder: '1.3.0'
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: 运行平台
      description: 如何进行部署的
      multiple: false
      options:
        - "local/server"
        - "docker/docker-compose"
        - "github action"
        - "others"
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: 问题描述
      description: 简明扼要的说明你遇到的问题以及对代码进行过自定义修改
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: 运行日志
      description: 请复制或截图完整的错误日志
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其他补充
